apiVersion: apps/v1
kind: Deployment
metadata:
  name: drasi-postgres
  labels:
    app: drasi-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drasi-postgres
  template:
    metadata:
      labels:
        app: drasi-postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_PASSWORD
          value: postgres
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_DB
          value: drasidb
        - name: POSTGRES_INITDB_ARGS
          value: "--data-checksums"
        args:
        - "postgres"
        - "-c"
        - "wal_level=logical"
        - "-c"
        - "max_wal_senders=8"
        - "-c"
        - "max_replication_slots=4"
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: drasi-postgres-service
spec:
  selector:
    app: drasi-postgres
  ports:
  - port: 5432
    targetPort: 5432
  type: ClusterIP
