apiVersion: v1
kind: Source
name: order-source
spec:
  kind: PostgreSQL
  properties:
    host: order-postgres-service.default.svc.cluster.local
    port: 5432
    user: postgres
    password: postgres
    database: orderdb
    ssl: false
    tables:
      - public.order_state