apiVersion: v1
kind: Source
name: product-source
spec:
  kind: PostgreSQL
  properties:
    host: product-postgres-service.default.svc.cluster.local
    port: 5432
    user: postgres
    password: postgres
    database: productdb
    ssl: false
    tables:
      - public.product_state