apiVersion: v1
kind: Source
name: user-source
spec:
  kind: PostgreSQL
  properties:
    host: user-postgres-service.default.svc.cluster.local
    port: 5432
    user: postgres
    password: postgres
    database: userdb
    ssl: false
    tables:
      - public.user_state