apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: product-state-store
  annotations:
    dapr.io/scopes: "product-service"
spec:
  type: state.postgresql
  version: v1
  metadata:
  - name: connectionString
    value: "host=product-postgres-service user=postgres password=postgres port=5432 dbname=productdb sslmode=disable"
  - name: tableName
    value: "product_state"
  - name: metadataTableName
    value: "product_metadata"
  - name: keyPrefix
    value: "product:"
  - name: keyType
    value: "string"
