apiVersion: apps/v1
kind: Deployment
metadata:
  name: all-details-direct
  labels:
    app: all-details-direct
spec:
  replicas: 1
  selector:
    matchLabels:
      app: all-details-direct
  template:
    metadata:
      labels:
        app: all-details-direct
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "all-details-direct"
        dapr.io/app-port: "5000"
        dapr.io/enable-api-logging: "true"
    spec:
      containers:
      - name: all-details-direct
        image: all-details-direct:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        env:
        - name: DAPR_HTTP_PORT
          value: "3500"
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: all-details-direct
spec:
  selector:
    app: all-details-direct
  ports:
  - port: 80
    targetPort: 5000
  type: ClusterIP
